CREATE TABLE PROPERTIES (
ID INT PRIMARY KEY,
ROOM_TYPE VARCHAR(30) NOT NULL,
DESCRIPTION VARCHAR(30) NOT NULL,
BOROUGH VARCHAR(30) NOT NULL,
AREA VARCHAR(30)NOT NULL,
PRICE INT NOT NULL,
HOST_NAME VARCHAR(30) NOT NULL,
LAST_REVIEW DATE NOT NULL
);